name: 'jira_analytics'
version: '1.0.0'
config-version: 2

profile: 'jira_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jira_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

# Conditional test configuration
vars:
  load_projects: true
  load_users: true

# Test configuration based on variables
tests:
  jira_analytics:
    +enabled: "{{ var('load_projects', true) and var('load_users', true) }}"
