name: 'jira_analytics'
version: '1.0.0'
config-version: 2

profile: 'jira_analytics'

model-paths: ["models"]
target-path: "target"
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jira_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
