version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jira_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dlt_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dlt_password}
      POSTGRES_DB: ${POSTGRES_DB:-jira_dw}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dlt_user} -d ${POSTGRES_DB:-jira_dw}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira_pipeline
    environment:
      - JIRA_SUBDOMAIN=${JIRA_SUBDOMAIN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-dlt_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dlt_password}
      - POSTGRES_DB=${POSTGRES_DB:-jira_dw}
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.dlt:/app/.dlt:ro
      - ./logs:/app/logs:rw
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: "no"

  grafana:
    image: grafana/grafana:latest
    container_name: jira_grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-postgresql-datasource
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-dlt_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dlt_password}
      - POSTGRES_DB=${POSTGRES_DB:-jira_dw}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped

volumes:
  postgres_data:
  grafana_data: