{
 "title": "Team Performance and Productivity",
 "tags": [
  "jira",
  "team"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Issues by Status by User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "jira_dw",
     "rawSql": "SELECT user_name, status_category, assigned_issues FROM jira_analytics.fct_user_performance LIMIT 50 "
    }
   ]
  },
  {
   "title": "Open vs. Closed Issues (Trend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "jira_dw",
     "rawSql": "WITH dates AS (\n    SELECT generate_series(\n      date_trunc('month', NOW()) - interval '6 months',\n    date_trunc('month', NOW()),\n    interval '1 month'\n  )::date as month_date\n),\nissues_by_month AS (\n    SELECT\n    date_trunc('month', created_date)::date as month,\n    COUNT(*) as created,\n    COUNT(CASE WHEN resolution_date IS NOT NULL THEN 1 END) as resolved\n  FROM\n    jira_analytics.fct_issues_details\n  GROUP BY\n    date_trunc('month', created_date)::date\n)\n\nSELECT\n  dates.month_date as time,\n  COALESCE(issues_by_month.created, 0) as \"Issues Criadas\",\n  COALESCE(issues_by_month.resolved, 0) as \"Issues Resolvidas\"\nFROM\n  dates\nLEFT JOIN\n  issues_by_month ON dates.month_date = issues_by_month.month\nORDER BY\n  dates.month_date"
    }
   ]
  },
  {
   "title": "Team Workload Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "jira_dw",
     "rawSql": "SELECT\n  user_name,\n  SUM(assigned_issues) as total_issues\nFROM\n  jira_analytics.fct_user_performance\nGROUP BY\n  user_name\nORDER BY\n  total_issues DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Individual Resolution Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "jira_dw",
     "rawSql": "SELECT\n  user_name,\n  SUM(assigned_issues) as total_issues,\n  ROUND(AVG(avg_days_to_resolution)::numeric, 2) as avg_days_to_resolution\nFROM\n  jira_analytics.fct_user_performance\nWHERE\n  avg_days_to_resolution IS NOT NULL\nGROUP BY\n  user_name\nORDER BY\n  avg_days_to_resolution ASC"
    }
   ]
  }
 ]
}