apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 2
      maxIdleConnsTime: 300
      connMaxLifetime: 3600
      postgresVersion: 1500
      timescaledb: false
    editable: true
