# dlt Configuration for Jira Pipeline

[general]
log_level = "INFO"

[load]
dev_mode = false
schema_evolution = false

[destination.postgres]
create_indexes = true
staging = false

[runtime]
dlthub_telemetry = true