name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Data Pipeline CI/CD"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build Docker Image
      run: |
        docker build -t jira-pipeline:staging .
        
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment..."
        # Add staging deployment logic here
        echo "✅ Staging deployment completed!"
        
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build Docker Image
      run: |
        docker build -t jira-pipeline:production .
        docker tag jira-pipeline:production jira-pipeline:latest
        
    - name: Deploy to Production
      run: |
        echo "Deploying to production environment..."
        # Add production deployment logic here
        echo "✅ Production deployment completed!"
        
    - name: Health Check
      run: |
        echo "Performing health check..."
        # Add health check logic here
        echo "✅ Health check passed!"
