name: Metrics Collection

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  collect-metrics:
    name: Collect Metrics
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Collect Pipeline Metrics
      run: |
        python monitor.py --collect-metrics
        
    - name: Upload Metrics
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-metrics
        path: metrics/
